In [1]:
import pandas as pd

In [ ]:
# 파일 경로를 따와서 넣을 수 있다. (변수에 넣고, encoding도 실행(만약 안되면) 그리고 pd.read_csv()로 불러온다.
# 다운로드 받고 ctrl+j눌린다음 링크 주소 복사를 볼 수 있음.
# utf-8 을 ms949로 자주 쓴다! 핫 키!

In [2]:
targetUrl = "https://www.data.go.kr/cmm/cmm/fileDownload.do?atchFileId=FILE_000000002477494&fileDetailSn=1&dataNm=%ED%95%9C%EA%B5%AD%EC%A3%BC%ED%83%9D%EA%B8%88%EC%9C%B5%EA%B3%B5%EC%82%AC_%EC%A7%80%EC%97%AD%EB%B3%84%20PIR%20%EB%B0%8F%20LIR_20200501"

In [3]:
indata = pd.read_csv(targetUrl, encoding = "ms949")

In [6]:
indata.tail()

,연도,월,전국(PIR),서울(PIR),부산(PIR),대구(PIR),인천(PIR),광주(PIR),대전(PIR),울산(PIR),...,세종(LIR),경기(LIR),강원(LIR),충북(LIR),충남(LIR),전북(LIR),전남(LIR),경북(LIR),경남(LIR),제주(LIR)
190,2020,1,4.47,5.44,4.84,5.16,4.39,4.76,4.52,4.11,...,2.63,2.39,1.90,1.76,1.87,1.94,1.85,1.80,2.02,2.13
191,2020,2,4.45,5.02,5.04,4.92,4.49,4.52,4.36,3.90,...,2.69,2.34,1.96,1.87,1.89,1.83,1.68,1.69,1.91,2.07
192,2020,3,4.76,5.12,5.22,5.20,4.76,5.04,4.74,4.11,...,2.22,2.56,2.13,1.98,2.03,1.97,1.89,1.95,2.23,2.27
193,2020,4,4.83,4.95,5.67,5.91,4.78,5.41,5.40,4.44,...,1.73,2.54,2.13,2.09,2.14,2.11,1.94,1.97,2.06,1.85
194,2020,5,4.56,4.88,7.01,5.44,4.56,3.16,4.72,5.77,...,0.00,2.23,2.44,1.08,1.65,1.04,1.68,1.99,2.17,0.96

In [22]:
targetUrl2 = "https://www.data.go.kr/cmm/cmm/fileDownload.do?atchFileId=FILE_000000002336443&fileDetailSn=1&dataNm=%ED%86%B5%EA%B3%84%EC%B2%AD_%EB%82%98%EB%9D%BC%ED%86%B5%EA%B3%84_%EC%9A%B0%ED%8E%B8%EB%B2%88%ED%98%B8_20211110"

indata2 = pd.read_csv(targetUrl2, encoding = "ms949")

In [23]:
indata2

,우편번호,우편번호순서,도이름,시군구이름,읍면동이름,리건물이름,동호,전체주소
0,137926,11,서울특별시,서초구,서초1동,NaN,1641-1~1641-13,서울특별시 서초구 서초1동 1641-1~1641-13
1,137927,11,서울특별시,서초구,서초3동,NaN,1451,서울특별시 서초구 서초3동 1451
2,137929,12,서울특별시,서초구,서초4동,서초교대e편한세상아파트,(101~106동),서울특별시 서초구 서초4동 서초교대e편한세상아파트 (101~106동)
3,137930,2,서울특별시,서초구,반포1동,반포자이아파트,(101~144동),서울특별시 서초구 반포1동 반포자이아파트 (101~144동)
4,137931,2,서울특별시,서초구,반포1동,삼호가든아파트,(501~503동),서울특별시 서초구 반포1동 삼호가든아파트 (501~503동)
...,...,...,...,...,...,...,...,...
52538,799821,31,경상북도,울릉군,북면,나리,NaN,경상북도 울릉군 북면 나리
52539,799822,21,경상북도,울릉군,북면,천부4리,NaN,경상북도 울릉군 북면 천부4리
52540,799822,11,경상북도,울릉군,북면,천부3리,NaN,경상북도 울릉군 북면 천부3리
52541,799822,1,경상북도,울릉군,북면,나리2리,NaN,경상북도 울릉군 북면 나리2리
52542,799823,1,경상북도,울릉군,북면,현포리,NaN,경상북도 울릉군 북면 현포리

# 4.json 데이터 불러오기

In [27]:
url = "https://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=MjQyODJiOGM0YzBmODQ1YTBkZDE4NzZkYmRjNmIzM2I=&format=json&jsonVD=Y&userStatsId=ddingddol/101/DT_1B040A3/2/1/20220405102832&prdSe=M&newEstPrdCnt=1"

In [32]:
try:
    json = pd.read_json(url)
except Exception as e:
    print(e)
json

,TBL_NM,PRD_DE,TBL_ID,ITM_NM,ITM_NM_ENG,ITM_ID,UNIT_NM,ORG_ID,UNIT_NM_ENG,C1_OBJ_NM,C1_OBJ_NM_ENG,DT,PRD_SE,C1,C1_NM,C1_NM_ENG
0,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51610695,M,0,전국,Whole country
1,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,25730584,M,0,전국,Whole country
2,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,25880111,M,0,전국,Whole country
3,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,9506778,M,11,서울특별시,Seoul
4,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,4613910,M,11,서울특별시,Seoul
5,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,4892868,M,11,서울특별시,Seoul
6,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,3343504,M,26,부산광역시,Busan
7,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,1634958,M,26,부산광역시,Busan
8,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,1708546,M,26,부산광역시,Busan
9,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,2380494,M,27,대구광역시,Daegu
10,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,1172632,M,27,대구광역시,Daegu
11,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,1207862,M,27,대구광역시,Daegu
12,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,2952699,M,28,인천광역시,Incheon
13,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,1478272,M,28,인천광역시,Incheon
14,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,1474427,M,28,인천광역시,Incheon
15,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1438463,M,29,광주광역시,Gwangju
16,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,711289,M,29,광주광역시,Gwangju
17,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,727174,M,29,광주광역시,Gwangju
18,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1450057,M,30,대전광역시,Daejeon
19,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,723361,M,30,대전광역시,Daejeon
20,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,726696,M,30,대전광역시,Daejeon
21,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1118010,M,31,울산광역시,Ulsan
22,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,574444,M,31,울산광역시,Ulsan
23,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,543566,M,31,울산광역시,Ulsan
24,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,377296,M,36,세종특별자치시,Sejong_si
25,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,188356,M,36,세종특별자치시,Sejong_si
26,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,188940,M,36,세종특별자치시,Sejong_si
27,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,13575936,M,41,경기도,Gyeonggi-do
28,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,6832830,M,41,경기도,Gyeonggi-do
29,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,6743106,M,41,경기도,Gyeonggi-do
30,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1539036,M,42,강원도,Gangwon-do
31,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,774522,M,42,강원도,Gangwon-do
32,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,764514,M,42,강원도,Gangwon-do
33,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1597484,M,43,충청북도,Chungcheongbuk-do
34,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,811004,M,43,충청북도,Chungcheongbuk-do
35,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,786480,M,43,충청북도,Chungcheongbuk-do
36,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,2119099,M,44,충청남도,Chungcheongnam-do
37,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,1083753,M,44,충청남도,Chungcheongnam-do
38,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,1035346,M,44,충청남도,Chungcheongnam-do
39,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1782205,M,45,전라북도,Jeollabuk-do
40,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,886928,M,45,전라북도,Jeollabuk-do
41,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,895277,M,45,전라북도,Jeollabuk-do
42,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,1829501,M,46,전라남도,Jeollanam-do
43,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,920971,M,46,전라남도,Jeollanam-do
44,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,908530,M,46,전라남도,Jeollanam-do
45,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,2619641,M,47,경상북도,Gyeongsangbuk-do
46,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,1320888,M,47,경상북도,Gyeongsangbuk-do
47,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,1298753,M,47,경상북도,Gyeongsangbuk-do
48,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,3303274,M,48,경상남도,Gyeongsangnam-do
49,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,1663146,M,48,경상남도,Gyeongsangnam-do
50,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,1640128,M,48,경상남도,Gyeongsangnam-do
51,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,677218,M,50,제주특별자치도,Jeju-do
52,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,남자인구수,Koreans (Male),T21,명,101,Person,행정구역(시군구)별,By Administrative District,339320,M,50,제주특별자치도,Jeju-do
53,행정구역(시군구)별 성별 인구수,202203,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,337898,M,50,제주특별자치도,Jeju-do

In [ ]:
# XML??  Extensible Markup Language

In [ ]:
# 개인 인증키
7MWa6h%2FzhFG0Gg3LEIzEQNscntTjt%2FbKeTyC1gcA4i9bYx7nFj336WmW0zXzUDK%2FNPQzC7iOla5fq%2BeUhFNEXw%3D%3D

In [2]:
url2 = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD=11110&DEAL_YMD=201512&serviceKey=AT33s775KYpJOkUBJu0dxkJuUeIfDIOJRzAH084EQS3JN%2BzFjErLHuk%2FGZa9L4gBTSGCzeA69tI9PwLp7B37IQ%3D%3D"

In [78]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd

In [79]:
resp = requests.get(url2)

In [80]:
resp.encoding = 'utf-8'

In [81]:
resp.text

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><거래금액>    82,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 사직동</법정동><아파트>광화문스페이스본(101동~105동)</아파트><월>12</월><일>10</일><전용면적>94.51</전용면적><중개사소재지> </중개사소재지><지번>9</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    60,000</거래금액><거래유형> </거래유형><건축년도>1981</건축년도><년>2015</년><법정동> 당주동</법정동><아파트>롯데미도파광화문빌딩</아파트><월>12</월><일>22</일><전용면적>149.95</전용면적><중개사소재지> </중개사소재지><지번>145</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   130,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>킹스매너</아파트><월>12</월><일>8</일><전용면적>194.43</전용면적><중개사소재지> </중개사소재지><지번>110-15</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   105,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁의아침2단지</아파트><월>12</월><일>14</일><전용면적>124.17</전용면적><중개사소재지> </중개사소재지><지번>71</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   120,000</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁파크팰리스</아파트><월>12</월><일>24</일><전용면적>146.33</전용면적><중개사소재지> </중개사소재지><지번>95</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>17</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>18</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    57,000</거래금액><거래유형> </거래유형><건축년도>2006</건축년도><년>2015</년><법정동> 명륜1가</법정동><아파트>렉스빌</아파트><월>12</월><일>29</일><전용면적>106.98</전용면적><중개사소재지> </중개사소재지><지번>19</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>1</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>18</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>10</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    49,800</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>19</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남3</아파트><월>12</월><일>19</일><전용면적>61.13</전용면적><중개사소재지> </중개사소재지><지번>237</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>2</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    19,500</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>3</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,900</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신이수</아파트><월>12</월><일>3</일><전용면적>68.06</전용면적><중개사소재지> </중개사소재지><지번>23-816</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    20,800</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>7</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,200</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>7</일><전용면적>64.66</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>10</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,950</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>11</일><전용면적>115.53</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    34,500</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>12</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,000</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>14</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,800</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>22</일><전용면적>106.62</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,300</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>23</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    50,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>24</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    12,300</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로아인스빌</아파트><월>12</월><일>2</일><전용면적>12.15</전용면적><중개사소재지> </중개사소재지><지번>1392-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>3</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>19</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    53,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>5</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>5</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    13,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>12</월><일>8</일><전용면적>15.09</전용면적><중개사소재지> </중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,500</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>8</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,000</거래금액><거래유형> </거래유형><건축년도>1997</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>동문(비동,씨동)(494-0)</아파트><월>12</월><일>9</일><전용면적>59.94</전용면적><중개사소재지> </중개사소재지><지번>494</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,900</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>14</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,900</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>14</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,500</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>15.76</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,000</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>14.48</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>19</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,700</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>22</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>26</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,800</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로유케이201</아파트><월>12</월><일>31</일><전용면적>12.01</전용면적><중개사소재지> </중개사소재지><지번>201-11</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>31</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,600</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 교북동</법정동><아파트>동아</아파트><월>12</월><일>7</일><전용면적>84.28</전용면적><중개사소재지> </중개사소재지><지번>101</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   115,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>벽산블루밍평창힐스</아파트><월>12</월><일>2</일><전용면적>210.53</전용면적><중개사소재지> </중개사소재지><지번>45</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   164,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>12</월><일>3</일><전용면적>219.775</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    31,500</거래금액><거래유형> </거래유형><건축년도>1998</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>삼성</아파트><월>12</월><일>6</일><전용면적>59.97</전용면적><중개사소재지> </중개사소재지><지번>596</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>12</일><전용면적>60</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>15</일><전용면적>114.9</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    62,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>16</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,400</거래금액><거래유형> </거래유형><건축년도>2015</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산2차아이파크</아파트><월>12</월><일>22</일><전용면적>84.0284</전용면적><중개사소재지> </중개사소재지><지번>88</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    61,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>25</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>49</totalCount></body></response>'

In [83]:
xmlobj = bs4.BeautifulSoup(resp.text,"lxml-xml")

In [36]:
xmlobj

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><거래금액>    82,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 사직동</법정동><아파트>광화문스페이스본(101동~105동)</아파트><월>12</월><일>10</일><전용면적>94.51</전용면적><중개사소재지> </중개사소재지><지번>9</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    60,000</거래금액><거래유형> </거래유형><건축년도>1981</건축년도><년>2015</년><법정동> 당주동</법정동><아파트>롯데미도파광화문빌딩</아파트><월>12</월><일>22</일><전용면적>149.95</전용면적><중개사소재지> </중개사소재지><지번>145</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   130,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>킹스매너</아파트><월>12</월><일>8</일><전용면적>194.43</전용면적><중개사소재지> </중개사소재지><지번>110-15</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   105,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁의아침2단지</아파트><월>12</월><일>14</일><전용면적>124.17</전용면적><중개사소재지> </중개사소재지><지번>71</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   120,000</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁파크팰리스</아파트><월>12</월><일>24</일><전용면적>146.33</전용면적><중개사소재지> </중개사소재지><지번>95</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>17</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>18</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    57,000</거래금액><거래유형> </거래유형><건축년도>2006</건축년도><년>2015</년><법정동> 명륜1가</법정동><아파트>렉스빌</아파트><월>12</월><일>29</일><전용면적>106.98</전용면적><중개사소재지> </중개사소재지><지번>19</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>1</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>18</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>10</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    49,800</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>19</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남3</아파트><월>12</월><일>19</일><전용면적>61.13</전용면적><중개사소재지> </중개사소재지><지번>237</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>2</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    19,500</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>3</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,900</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신이수</아파트><월>12</월><일>3</일><전용면적>68.06</전용면적><중개사소재지> </중개사소재지><지번>23-816</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    20,800</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>7</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,200</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>7</일><전용면적>64.66</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>10</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,950</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>11</일><전용면적>115.53</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    34,500</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>12</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,000</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>14</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,800</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>22</일><전용면적>106.62</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,300</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>23</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    50,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>24</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    12,300</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로아인스빌</아파트><월>12</월><일>2</일><전용면적>12.15</전용면적><중개사소재지> </중개사소재지><지번>1392-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>3</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>19</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    53,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>5</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>5</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    13,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>12</월><일>8</일><전용면적>15.09</전용면적><중개사소재지> </중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,500</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>8</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,000</거래금액><거래유형> </거래유형><건축년도>1997</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>동문(비동,씨동)(494-0)</아파트><월>12</월><일>9</일><전용면적>59.94</전용면적><중개사소재지> </중개사소재지><지번>494</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,900</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>14</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,900</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>14</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,500</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>15.76</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,000</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>14.48</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>19</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,700</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>22</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>26</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,800</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로유케이201</아파트><월>12</월><일>31</일><전용면적>12.01</전용면적><중개사소재지> </중개사소재지><지번>201-11</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>31</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,600</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 교북동</법정동><아파트>동아</아파트><월>12</월><일>7</일><전용면적>84.28</전용면적><중개사소재지> </중개사소재지><지번>101</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   115,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>벽산블루밍평창힐스</아파트><월>12</월><일>2</일><전용면적>210.53</전용면적><중개사소재지> </중개사소재지><지번>45</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   164,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>12</월><일>3</일><전용면적>219.775</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    31,500</거래금액><거래유형> </거래유형><건축년도>1998</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>삼성</아파트><월>12</월><일>6</일><전용면적>59.97</전용면적><중개사소재지> </중개사소재지><지번>596</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>12</일><전용면적>60</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>15</일><전용면적>114.9</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    62,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>16</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,400</거래금액><거래유형> </거래유형><건축년도>2015</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산2차아이파크</아파트><월>12</월><일>22</일><전용면적>84.0284</전용면적><중개사소재지> </중개사소재지><지번>88</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    61,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>25</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>49</totalCount></body></response>

In [84]:
itemsTag = xmlobj.find(name="items")

In [88]:
itemsTag

<items><item><거래금액>    82,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 사직동</법정동><아파트>광화문스페이스본(101동~105동)</아파트><월>12</월><일>10</일><전용면적>94.51</전용면적><중개사소재지> </중개사소재지><지번>9</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    60,000</거래금액><거래유형> </거래유형><건축년도>1981</건축년도><년>2015</년><법정동> 당주동</법정동><아파트>롯데미도파광화문빌딩</아파트><월>12</월><일>22</일><전용면적>149.95</전용면적><중개사소재지> </중개사소재지><지번>145</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   130,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>킹스매너</아파트><월>12</월><일>8</일><전용면적>194.43</전용면적><중개사소재지> </중개사소재지><지번>110-15</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   105,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁의아침2단지</아파트><월>12</월><일>14</일><전용면적>124.17</전용면적><중개사소재지> </중개사소재지><지번>71</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   120,000</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁파크팰리스</아파트><월>12</월><일>24</일><전용면적>146.33</전용면적><중개사소재지> </중개사소재지><지번>95</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>17</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>18</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    57,000</거래금액><거래유형> </거래유형><건축년도>2006</건축년도><년>2015</년><법정동> 명륜1가</법정동><아파트>렉스빌</아파트><월>12</월><일>29</일><전용면적>106.98</전용면적><중개사소재지> </중개사소재지><지번>19</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>1</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>18</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>10</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    49,800</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>19</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남3</아파트><월>12</월><일>19</일><전용면적>61.13</전용면적><중개사소재지> </중개사소재지><지번>237</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>2</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    19,500</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>3</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,900</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신이수</아파트><월>12</월><일>3</일><전용면적>68.06</전용면적><중개사소재지> </중개사소재지><지번>23-816</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    20,800</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>7</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,200</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>7</일><전용면적>64.66</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>10</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,950</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>11</일><전용면적>115.53</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    34,500</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>12</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,000</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>14</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,800</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>22</일><전용면적>106.62</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,300</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>23</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    50,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>24</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    12,300</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로아인스빌</아파트><월>12</월><일>2</일><전용면적>12.15</전용면적><중개사소재지> </중개사소재지><지번>1392-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>3</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>19</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    53,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>5</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>5</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    13,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>12</월><일>8</일><전용면적>15.09</전용면적><중개사소재지> </중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,500</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>8</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,000</거래금액><거래유형> </거래유형><건축년도>1997</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>동문(비동,씨동)(494-0)</아파트><월>12</월><일>9</일><전용면적>59.94</전용면적><중개사소재지> </중개사소재지><지번>494</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,900</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>14</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,900</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>14</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,500</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>15.76</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,000</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>14.48</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>19</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,700</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>22</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>26</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,800</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로유케이201</아파트><월>12</월><일>31</일><전용면적>12.01</전용면적><중개사소재지> </중개사소재지><지번>201-11</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>31</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,600</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 교북동</법정동><아파트>동아</아파트><월>12</월><일>7</일><전용면적>84.28</전용면적><중개사소재지> </중개사소재지><지번>101</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   115,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>벽산블루밍평창힐스</아파트><월>12</월><일>2</일><전용면적>210.53</전용면적><중개사소재지> </중개사소재지><지번>45</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   164,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>12</월><일>3</일><전용면적>219.775</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    31,500</거래금액><거래유형> </거래유형><건축년도>1998</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>삼성</아파트><월>12</월><일>6</일><전용면적>59.97</전용면적><중개사소재지> </중개사소재지><지번>596</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>12</일><전용면적>60</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>15</일><전용면적>114.9</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    62,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>16</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,400</거래금액><거래유형> </거래유형><건축년도>2015</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산2차아이파크</아파트><월>12</월><일>22</일><전용면적>84.0284</전용면적><중개사소재지> </중개사소재지><지번>88</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    61,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>25</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item></items>

In [85]:
itemTag = itemsTag.findAll(name="item")

In [89]:
itemTag

[<item><거래금액>    82,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 사직동</법정동><아파트>광화문스페이스본(101동~105동)</아파트><월>12</월><일>10</일><전용면적>94.51</전용면적><중개사소재지> </중개사소재지><지번>9</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    60,000</거래금액><거래유형> </거래유형><건축년도>1981</건축년도><년>2015</년><법정동> 당주동</법정동><아파트>롯데미도파광화문빌딩</아파트><월>12</월><일>22</일><전용면적>149.95</전용면적><중개사소재지> </중개사소재지><지번>145</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>   130,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>킹스매너</아파트><월>12</월><일>8</일><전용면적>194.43</전용면적><중개사소재지> </중개사소재지><지번>110-15</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>   105,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁의아침2단지</아파트><월>12</월><일>14</일><전용면적>124.17</전용면적><중개사소재지> </중개사소재지><지번>71</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>   120,000</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁파크팰리스</아파트><월>12</월><일>24</일><전용면적>146.33</전용면적><중개사소재지> </중개사소재지><지번>95</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>17</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>18</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    57,000</거래금액><거래유형> </거래유형><건축년도>2006</건축년도><년>2015</년><법정동> 명륜1가</법정동><아파트>렉스빌</아파트><월>12</월><일>29</일><전용면적>106.98</전용면적><중개사소재지> </중개사소재지><지번>19</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    44,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>1</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>18</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>10</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    49,800</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>19</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남3</아파트><월>12</월><일>19</일><전용면적>61.13</전용면적><중개사소재지> </중개사소재지><지번>237</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>2</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    19,500</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>3</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    39,900</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신이수</아파트><월>12</월><일>3</일><전용면적>68.06</전용면적><중개사소재지> </중개사소재지><지번>23-816</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    20,800</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>7</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    27,200</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>7</일><전용면적>64.66</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    39,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>10</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    39,950</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>11</일><전용면적>115.53</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    34,500</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>12</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    37,000</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>14</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    42,800</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>22</일><전용면적>106.62</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    37,300</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>23</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    50,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>24</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    12,300</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로아인스빌</아파트><월>12</월><일>2</일><전용면적>12.15</전용면적><중개사소재지> </중개사소재지><지번>1392-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>3</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>19</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    53,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>5</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>5</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    13,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>12</월><일>8</일><전용면적>15.09</전용면적><중개사소재지> </중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    11,500</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>8</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    27,000</거래금액><거래유형> </거래유형><건축년도>1997</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>동문(비동,씨동)(494-0)</아파트><월>12</월><일>9</일><전용면적>59.94</전용면적><중개사소재지> </중개사소재지><지번>494</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    44,900</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>14</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    11,900</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>14</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    10,500</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>15.76</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    10,000</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>14.48</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>19</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    39,700</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>22</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    52,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>26</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    10,800</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로유케이201</아파트><월>12</월><일>31</일><전용면적>12.01</전용면적><중개사소재지> </중개사소재지><지번>201-11</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    52,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>31</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    44,600</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 교북동</법정동><아파트>동아</아파트><월>12</월><일>7</일><전용면적>84.28</전용면적><중개사소재지> </중개사소재지><지번>101</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>   115,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>벽산블루밍평창힐스</아파트><월>12</월><일>2</일><전용면적>210.53</전용면적><중개사소재지> </중개사소재지><지번>45</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>   164,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>12</월><일>3</일><전용면적>219.775</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    31,500</거래금액><거래유형> </거래유형><건축년도>1998</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>삼성</아파트><월>12</월><일>6</일><전용면적>59.97</전용면적><중개사소재지> </중개사소재지><지번>596</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    39,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>12</일><전용면적>60</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    63,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>15</일><전용면적>114.9</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    62,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>16</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    63,400</거래금액><거래유형> </거래유형><건축년도>2015</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산2차아이파크</아파트><월>12</월><일>22</일><전용면적>84.0284</전용면적><중개사소재지> </중개사소재지><지번>88</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>    61,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>25</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>]

In [105]:
eachTag = itemTag[0]

In [104]:
eachTag

<item><거래금액>    60,000</거래금액><거래유형> </거래유형><건축년도>1981</건축년도><년>2015</년><법정동> 당주동</법정동><아파트>롯데미도파광화문빌딩</아파트><월>12</월><일>22</일><전용면적>149.95</전용면적><중개사소재지> </중개사소재지><지번>145</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>

In [92]:
columns = eachTag.findAll()

In [95]:
columns[0]

In [65]:
columns[0].name

'거래금액'

In [67]:
columns[0].text

'    82,500'

In [100]:
rowList = []
columnList = []

In [ ]:
columnList.append()

In [ ]:
columnList.append()
rowList.append(columnList)
columnList=[]

In [101]:
for j in range(0, len(columns)):
    rowList = columns[j].findAll()
    for i in range(0, len(columns)):
        columnList.append(columns[i].name)
        columnList.append(columns[i].text)
        rowList.append(columnList)
        columnList = []

In [102]:
pd.DataFrame(rowList)

          0                    1
0      거래금액               82,500
1      거래유형
2      건축년도                 2008
3         년                 2015
4       법정동                  사직동
5       아파트  광화문스페이스본(101동~105동)
6         월                   12
7         일                   10
8      전용면적                94.51
9    중개사소재지
10       지번                    9
11     지역코드                11110
12        층                   11
13  해제사유발생일
14     해제여부